const CAB_HIPSTER_COLORS = ['PINK'];

const CAB_SERVICE_RANGE_IN_KM = 10;

const CAB_FARE = {
    PER_MIN: 1,
    PER_KM: 2,
    COLOR_PREFERENCE: 5,
};

const FARE_CURRENCY = 'DOGE';

export { CAB_HIPSTER_COLORS, CAB_SERVICE_RANGE_IN_KM, CAB_FARE, FARE_CURRENCY };
